language: java

jdk:
  - oraclejdk9
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash) -s build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml